apiVersion: v1
kind: Service
metadata:
  name: appointment
spec:
  selector:
    app: appointment
  type: NodePort
  ports:
    - name: http
      port: 8085
      nodePort: 30005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment
spec:
  selector:
    matchLabels:
      app: appointment
  replicas: 1
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
        - name: server
          image: r4bc1/appointment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8085

---